export const SET_IMPLICIT_GRANT_CREDENTIALS = "SET_IMPLICIT_GRANT_CREDENTIALS";
export const SET_BOARD = "SET_BOARD";
export const SET_SELECTED = "SET_SELECTED";
export const SET_AUTHENTICATION_STATUS = "SET_AUTHENTICATION_STATUS";