export const SET_IMPLICIT_GRANT_CREDENTIALS = "SET_IMPLICIT_GRANT_CREDENTIALS";
export const SET_BOARD = "SET_BOARD";
export const SET_SELECTED = "SET_SELECTED";
export const SET_AUTHENTICATION_STATUS = "SET_AUTHENTICATION_STATUS";
export const SET_PAGE = "SET_PAGE";
export const SET_AUTHENTICATION_CREDENTIALS = "SET_AUTHENTICATION_CREDENTIALS";
export const JOIN_GAME = "JOIN_GAME";
export const SET_SETTINGS = "SET_SETTINGS";